fileHandle = open('F:\\python\\Python\\Luminar\Python_Django\\LUMINAR\\files\\lastline.txt',"r" )
print("filehandle variable: ",fileHandle,"\nType of filehandle variable",type(fileHandle))
lineList = fileHandle.readlines()
fileHandle.close()
print (lineList)
print ("The last line is:")
print (lineList[-1])